In [1]:
import numpy as np


In [2]:
# !pwd ## El simbolo "!" indica que es un comando para la terminal

In [3]:
# pip install <package> ## Es la sintaxis comun para descargar paquetes de python

In [4]:
# !python3 -m pip install numpy  ## Codigo para instalar numpy en Linux/Mac
# !python -m pip install numpy ## Codigo para instalar numpy en Windows

# ND Arreglos en Numpy

In [5]:
arr1 = np.array([1, 2, 3])

In [6]:
print(arr1)

[1 2 3]


In [7]:
type(arr1)

numpy.ndarray

In [8]:
dir(arr1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [9]:
lista1 = [1, 1.1, "", True]
np.asarray(lista1)

array(['1', '1.1', '', 'True'], dtype='<U32')

In [10]:
arr2 = np.asarray([1, 2, 3, 4, 5])

In [11]:
arr2.shape # Nos devuelve las dimensiones del arreglo

(5,)

In [12]:
arr2.dtype # El tipo de razon

dtype('int32')

In [13]:
len(arr2)

5

## Lista de listas

In [14]:
lista2 = [[1, 2, 3], [4, 5, 6]]

In [15]:
type(lista2)

list

In [16]:
lista2[0][0]

1

In [17]:
arr3 = np.asarray(lista2)

In [18]:
type(arr3)

numpy.ndarray

In [19]:
len(arr3)

2

In [20]:
arr3.shape

(2, 3)

In [21]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr3[0, 0]

1

In [23]:
arr3[:, :2]

array([[1, 2],
       [4, 5]])

In [24]:
arr3.size

6

In [25]:
arr3.min()

1

In [26]:
arr3.max()

6

In [27]:
1920 * 1080 * 3 # Cantidad de datos de una imagen Full HD a color

6220800

In [28]:
arr3.mean()

3.5

In [29]:
arr3.std() # Caclular la desviacion estandar

1.707825127659933

In [30]:
np.mean(arr3)

3.5

## Operadores Aritmeticos

In [31]:
arr3 + 1 # Element-wise

array([[2, 3, 4],
       [5, 6, 7]])

In [32]:
arr3 -10

array([[-9, -8, -7],
       [-6, -5, -4]])

In [33]:
arr3 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [34]:
arr3 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [35]:
arr3 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [36]:
arr3 + arr3

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [37]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

# Copiar Arreglos

In [38]:
tmp = arr3 # Aunque modifiquemos arr3 esta va a afectar a temp debido a que numpy trabaja la asignacion como un apuntador

In [39]:
tmp

array([[1, 2, 3],
       [4, 5, 6]])

### Metodo Ideal para Copiar Arreglos

In [40]:
tmp = arr3.copy()

# Random

In [41]:
np.random.random() # Genera numeros aleatorios entre 0 y 1 (el 1 no lo toca)

0.9989524557955484

In [42]:
np.random.randint(10) # El parametro es un limite superior el cual no toca

6

In [43]:
np.random.randint(10, size=(10, 10))

array([[0, 7, 5, 7, 2, 6, 5, 7, 9, 2],
       [1, 8, 4, 3, 6, 2, 7, 8, 3, 6],
       [5, 2, 5, 2, 9, 8, 3, 2, 1, 4],
       [9, 5, 6, 9, 0, 5, 8, 4, 7, 0],
       [4, 9, 3, 4, 9, 6, 6, 3, 1, 5],
       [6, 7, 4, 5, 2, 2, 5, 2, 9, 8],
       [7, 8, 7, 7, 1, 3, 4, 5, 8, 2],
       [5, 4, 4, 7, 1, 3, 0, 5, 6, 2],
       [2, 5, 4, 1, 0, 1, 8, 3, 6, 3],
       [4, 0, 0, 1, 4, 3, 2, 2, 5, 0]])

In [44]:
np.random.seed(123)

In [45]:
np.random.randint(10, size=(10, 10))

array([[2, 2, 6, 1, 3, 9, 6, 1, 0, 1],
       [9, 0, 0, 9, 3, 4, 0, 0, 4, 1],
       [7, 3, 2, 4, 7, 2, 4, 8, 0, 7],
       [9, 3, 4, 6, 1, 5, 6, 2, 1, 8],
       [3, 5, 0, 2, 6, 2, 4, 4, 6, 3],
       [0, 6, 4, 7, 6, 7, 1, 5, 7, 9],
       [2, 4, 8, 1, 2, 1, 1, 3, 5, 9],
       [0, 8, 1, 6, 3, 3, 5, 9, 7, 9],
       [2, 3, 3, 3, 8, 6, 9, 7, 6, 3],
       [9, 6, 6, 6, 1, 3, 4, 3, 1, 0]])